"""
Pass 3 — Canonicalize topic labels per pillar.

Collects all raw_topic labels per pillar, sends them to the LLM which merges
duplicates/near-duplicates into 4–8 canonical labels per pillar, then remaps
all chunks to their canonical topic.

Usage:
    python pipeline/04_pass3_canonicalize.py [--pillar PILLAR_ID]
"""
import json
import re
import sqlite3
import sys
from pathlib import Path

import anthropic

sys.path.insert(0, str(Path(__file__).parent))
from config import DB_PATH, MODEL_CANON

client = anthropic.Anthropic()

CANON_PROMPT = """You are canonicalizing subtopic labels from Canada's AI strategy consultation for the pillar: "{pillar}".

Below is a list of raw topic labels generated by an LLM when labeling individual response chunks.
Many are duplicates, near-duplicates, or slight variations of the same concept.

Your task:
1. Identify 4–8 distinct canonical topics that cover this pillar's content.
2. Map every raw label to exactly one canonical label.
3. Canonical labels should be 3–7 words, plain English, specific (not vague).
4. Return ONLY a JSON object: {{"canonical_topics": ["label1", "label2", ...], "mapping": {{"raw label": "canonical label", ...}}}}

Raw topic labels (with occurrence counts):
{labels_json}
"""


def slugify(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "-", text)
    return text[:80]


def canonicalize_pillar(con: sqlite3.Connection, pillar_id: str) -> int:
    # Collect raw topics and their counts
    rows = con.execute(
        """
        SELECT raw_topic, COUNT(*) as cnt
        FROM chunks
        WHERE pillar_id = ? AND labeled = 1 AND raw_topic IS NOT NULL AND raw_topic != ''
        GROUP BY raw_topic
        ORDER BY cnt DESC
        """,
        (pillar_id,),
    ).fetchall()

    if not rows:
        print(f"  No labeled chunks for {pillar_id}. Run Pass 2 first.")
        return 0

    labels_json = json.dumps([{"label": r[0], "count": r[1]} for r in rows], ensure_ascii=False, indent=2)
    pillar_label = pillar_id.replace("-", " ").title()
    prompt = CANON_PROMPT.format(pillar=pillar_label, labels_json=labels_json)

    print(f"  {len(rows)} distinct raw labels → asking LLM to canonicalize …")

    try:
        msg = client.messages.create(
            model=MODEL_CANON,
            max_tokens=4096,
            messages=[{"role": "user", "content": prompt}],
        )
        raw = msg.content[0].text.strip()
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw)
        result = json.loads(raw)
    except Exception as e:
        print(f"  [ERROR] canonicalize: {e}")
        return 0

    canonical_topics: list[str] = result.get("canonical_topics", [])
    mapping: dict[str, str] = result.get("mapping", {})

    # Store raw→canonical mapping
    for raw_label, canonical_label in mapping.items():
        con.execute(
            "INSERT OR REPLACE INTO raw_topic_map (pillar_id, raw_label, canonical_label) VALUES (?,?,?)",
            (pillar_id, raw_label, canonical_label),
        )

    # Apply canonical topic to all chunks
    for raw_label, canonical_label in mapping.items():
        con.execute(
            "UPDATE chunks SET canonical_topic=? WHERE pillar_id=? AND raw_topic=?",
            (canonical_label, pillar_id, raw_label),
        )

    # Upsert canonical_topics table
    for label in canonical_topics:
        topic_id = slugify(label)
        con.execute(
            """
            INSERT INTO canonical_topics (pillar_id, topic_id, label)
            VALUES (?,?,?)
            ON CONFLICT(pillar_id, topic_id) DO UPDATE SET label=excluded.label
            """,
            (pillar_id, topic_id, label),
        )

    con.commit()
    print(f"  {len(canonical_topics)} canonical topics created, {len(mapping)} labels remapped.")
    return len(canonical_topics)


def compute_topic_scores(con: sqlite3.Connection, pillar_id: str) -> None:
    """After canonicalization, compute aggregate scores per topic."""
    topics = con.execute(
        "SELECT topic_id, label FROM canonical_topics WHERE pillar_id=?",
        (pillar_id,),
    ).fetchall()

    for topic_id, label in topics:
        # Public stats
        pub_rows = con.execute(
            """
            SELECT sentiment, SUM(priority_score)
            FROM chunks
            WHERE pillar_id=? AND canonical_topic=? AND source='public' AND labeled=1
            GROUP BY sentiment
            ORDER BY SUM(priority_score) DESC
            """,
            (pillar_id, label),
        ).fetchall()

        pub_count = con.execute(
            "SELECT COUNT(*) FROM chunks WHERE pillar_id=? AND canonical_topic=? AND source='public'",
            (pillar_id, label),
        ).fetchone()[0]

        pub_score_raw = sum(r[1] for r in pub_rows if r[1]) if pub_rows else 0
        dom_pub_sent = pub_rows[0][0] if pub_rows else "neutral"

        # Expert stats
        exp_rows = con.execute(
            """
            SELECT sentiment, SUM(priority_score)
            FROM chunks
            WHERE pillar_id=? AND canonical_topic=? AND source='expert' AND labeled=1
            GROUP BY sentiment
            ORDER BY SUM(priority_score) DESC
            """,
            (pillar_id, label),
        ).fetchall()

        exp_count = con.execute(
            "SELECT COUNT(*) FROM chunks WHERE pillar_id=? AND canonical_topic=? AND source='expert'",
            (pillar_id, label),
        ).fetchone()[0]

        exp_score_raw = sum(r[1] for r in exp_rows if r[1]) if exp_rows else 0
        dom_exp_sent = exp_rows[0][0] if exp_rows else "neutral"

        # Normalize scores to 0–10 scale (max raw = 9 per chunk * up to ~1000 chunks)
        # We normalize within the pillar after computing all topics
        # Store raw for now; normalization happens in export script

        sentiments_match = dom_pub_sent == dom_exp_sent
        delta = round(exp_score_raw - pub_score_raw, 2)  # temporary; will be normalized in export

        if sentiments_match:
            alignment_status = "aligned"
        elif abs(delta) < 0.15:
            alignment_status = "tension"
        else:
            alignment_status = "diverges"

        con.execute(
            """
            UPDATE canonical_topics
            SET public_score=?, expert_score=?, delta=?, alignment_status=?,
                dominant_public_sentiment=?, dominant_expert_sentiment=?,
                public_chunk_count=?, expert_chunk_count=?
            WHERE pillar_id=? AND topic_id=?
            """,
            (
                pub_score_raw, exp_score_raw, delta, alignment_status,
                dom_pub_sent, dom_exp_sent,
                pub_count, exp_count,
                pillar_id, topic_id,
            ),
        )

    con.commit()


def main() -> None:
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--pillar", help="Limit to one pillar ID")
    args = parser.parse_args()

    con = sqlite3.connect(DB_PATH)
    pillars = con.execute("SELECT DISTINCT pillar_id FROM chunks WHERE labeled=1 ORDER BY pillar_id").fetchall()
    pillar_ids = [p[0] for p in pillars]

    if args.pillar:
        pillar_ids = [p for p in pillar_ids if p == args.pillar]

    for pid in pillar_ids:
        print(f"\n→ Canonicalizing: {pid}")
        n = canonicalize_pillar(con, pid)
        if n > 0:
            print(f"  Computing topic scores …")
            compute_topic_scores(con, pid)

    print("\nPass 3 complete.")
    con.close()


if __name__ == "__main__":
    main()
